
function initResourcesFilter(){const b=document.querySelectorAll('.filter-btn'),i=document.querySelectorAll('#resourceList .resource');if(!b.length)return;b.forEach(x=>x.addEventListener('click',()=>{b.forEach(y=>y.classList.remove('active'));x.classList.add('active');const f=x.dataset.filter;i.forEach(it=>it.style.display=f==='all'||it.dataset.cat===f?'block':'none')}))}
function initAuthorSearch(){const input=document.getElementById('authorSearch'),cards=document.querySelectorAll('.author-card');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();cards.forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)?'block':'none')})}
let currentQuizKey=null;
function initQuiz(){const menu=document.getElementById('quizMenu'),app=document.getElementById('quizApp');if(!menu||!app||typeof QUIZ_SETS==='undefined')return;menu.innerHTML=Object.entries(QUIZ_SETS).map(([key,quiz],idx)=>`<button class="quiz-choice ${idx===0?'active':''}" data-quiz="${key}"><strong>${quiz.title}</strong><br><span class="small">${quiz.description}</span></button>`).join('');menu.querySelectorAll('.quiz-choice').forEach(btn=>btn.addEventListener('click',()=>{menu.querySelectorAll('.quiz-choice').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderQuiz(btn.dataset.quiz)}));renderQuiz(Object.keys(QUIZ_SETS)[0]);updateLastQuizScore()}
function renderQuiz(key){currentQuizKey=key;const quiz=QUIZ_SETS[key],app=document.getElementById('quizApp');app.innerHTML=`<h2>${quiz.title}</h2><p class="small">${quiz.description}</p><hr class="soft"><form id="currentQuizForm">${quiz.questions.map((q,i)=>`<div class="quiz-question"><h3>Question ${i+1}</h3><p>${q.question}</p><div class="options">${q.options.map((opt,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"><span>${opt}</span></label>`).join('')}</div></div>`).join('')}<button type="button" class="btn secondary" onclick="submitQuiz()">Valider le quiz</button> <button type="button" class="btn ghost" onclick="renderQuiz(currentQuizKey)">Réinitialiser</button></form><div id="quizResult" class="quiz-result"></div>`}
function submitQuiz(){const quiz=QUIZ_SETS[currentQuizKey],form=document.getElementById('currentQuizForm');let score=0,answered=0,cor=[];quiz.questions.forEach((q,i)=>{const s=form.querySelector(`input[name="q${i}"]:checked`);if(s){answered++;const v=Number(s.value),ok=v===q.answer;if(ok)score++;cor.push({i:i+1,q:q.question,s:q.options[v],c:q.options[q.answer],ok,e:q.explanation})}else cor.push({i:i+1,q:q.question,s:'Pas de réponse',c:q.options[q.answer],ok:false,e:q.explanation})});const r=document.getElementById('quizResult');r.style.display='block';if(answered<quiz.questions.length){r.innerHTML=`<h2>Quiz incomplet</h2><p>Tu as répondu à ${answered}/${quiz.questions.length} questions.</p>`;r.scrollIntoView({behavior:'smooth'});return}const pct=Math.round(score/quiz.questions.length*100),msg=pct>=85?'Très bon niveau de maîtrise.':pct>=65?'Bon socle, quelques points à retravailler.':'À reprendre tranquillement en équipe ou en auto-formation.';const hist=JSON.parse(localStorage.getItem('pe_quiz_history')||'[]');hist.unshift({quiz:quiz.title,score,total:quiz.questions.length,percent:pct,date:new Date().toLocaleDateString('fr-FR')});localStorage.setItem('pe_quiz_history',JSON.stringify(hist.slice(0,10)));r.innerHTML=`<h2>Résultat : ${score}/${quiz.questions.length} (${pct} %)</h2><p>${msg}</p><h3>Correction</h3>${cor.map(c=>`<div class="correction-item"><p><strong>Question ${c.i} :</strong> ${c.q}</p><p class="${c.ok?'correct':'wrong'}">Ta réponse : ${c.s}</p><p>Bonne réponse : ${c.c}</p><p class="small">${c.e}</p></div>`).join('')}`;updateLastQuizScore();r.scrollIntoView({behavior:'smooth'})}
function updateLastQuizScore(){const t=document.getElementById('lastQuizScore');if(!t)return;const h=JSON.parse(localStorage.getItem('pe_quiz_history')||'[]');t.innerHTML=h.length?`${h[0].quiz}<br><strong>${h[0].score}/${h[0].total}</strong> (${h[0].percent} %) — ${h[0].date}`:'Aucun quiz terminé sur cet appareil.'}
function clearQuizHistory(){localStorage.removeItem('pe_quiz_history');updateLastQuizScore()}
document.addEventListener('DOMContentLoaded',()=>{initResourcesFilter();initAuthorSearch();initQuiz()});
